# Generated by Django 6.1.1 on 2026-09-19 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ram', 'Ram'), ('budh', 'budh'), ('Shankar', 'Shankar'), ('Vyas', 'Vyas'), ('Meera', 'Meera'), ('Krishna', 'Krishna'), ('Gandhi', 'Gandhi'), ('Ashok', 'Ashok'), ('Malviya', 'Malviya'), ('CVR', 'CVR'), ('SR', 'SR'), ('RP', 'RP'), ('VK', 'VK'), ('Bhagirath', 'Bhagirath')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BITS_Competition.hostel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brief', models.TextField()),
                ('points', models.IntegerField()),
                ('Codename', models.CharField(max_length=100)),
                ('Difficulty', models.IntegerField()),
                ('Status', models.CharField(choices=[('unclaimed', 'unclaimed'), ('in_progress', 'in_progress'), ('cracked', 'cracked'), ('expired', 'expired')], default='unclaimed', max_length=100)),
                ('Deadline', models.DateTimeField()),
                ('participant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BITS_Competition.participant')),
            ],
        ),
    ]
