# Generated by Django 6.1.1 on 2026-09-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BITS_Competition', '0001_initial'),
    ]

    operations = [
    ]
