# Generated by Django 6.1.1 on 2026-09-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BITS_Competition', '0002_auto_20260920_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='Status',
            field=models.CharField(max_length=100),
        ),
    ]
