# Generated by Django 6.1.1 on 2026-09-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BITS_Competition', '0004_organiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='name',
        ),
    ]
