# Generated by Django 6.1.1 on 2026-09-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BITS_Competition', '0005_remove_mission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='crcked_missions',
            field=models.ManyToManyField(blank=True, to='BITS_Competition.mission'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
