# Generated by Django 6.1.1 on 2026-09-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BITS_Competition', '0006_hostel_crcked_missions_hostel_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='crcked_missions',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='score',
        ),
    ]
