# Generated by Django 6.1.1 on 2026-09-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BITS_Competition', '0007_remove_hostel_crcked_missions_remove_hostel_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='Difficulty',
            field=models.CharField(max_length=100),
        ),
    ]
